[package]
name = "jpeg-encoder"
version = "0.0.1"
authors = ["Volker Ströbel <volkerstroebel@mysurdity.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "JPEG encoder"
categories = ["multimedia::images"]
keywords = ["jpg", "jpeg", "encoder", "image"]
readme = "README.md"
repository = "https://github.com/vstroebel/jpeg-encoder"

[dependencies]

[dev-dependencies]
image = { version = "0.23", default-features = false }
jpeg-decoder = "0.1.22"
criterion = "0.3"

[profile.dev]
opt-level = 1

[[bench]]
name = "encode"
harness = false