[package]
name = "jpeg-encoder"
version = "0.4.1"
authors = ["Volker Ströbel <volkerstroebel@mysurdity.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "JPEG encoder"
categories = ["multimedia::images"]
keywords = ["jpg", "jpeg", "encoder", "image"]
readme = "README.md"
repository = "https://github.com/vstroebel/jpeg-encoder"

[features]
default = ["std"]
simd = ["std"]
std = []

[dependencies]

[dev-dependencies]
jpeg-decoder = "0.2"
criterion = "0.3"

[profile.dev]
opt-level = 1

[[bench]]
name = "encode"
harness = false
