[package]
name = "jpeg-encoder"
version = "0.1.0"
authors = ["Volker Ströbel <volkerstroebel@mysurdity.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
jpeg-decoder = "0.1.22"

[profile.dev]
opt-level = 1